# Generated by Django 6.0.2 on 2026-02-17 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Type Description',
                'verbose_name_plural': 'Type Descriptions',
            },
        ),
        migrations.CreateModel(
            name='ConstructionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('stage', models.CharField(blank=True, default='', max_length=20)),
                ('lc_stage', models.CharField(blank=True, default='', max_length=20, verbose_name='LC-Stage')),
                ('estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='QTY')),
                ('supplies_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tax/Fees')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('invoiced_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Invoiced Amt')),
                ('posted', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('Inv', 'Invoice')], default='', max_length=10)),
                ('lm', models.CharField(blank=True, choices=[('L', 'Labor'), ('M', 'Materials'), ('U', 'Utility'), ('X', 'Transfer')], default='', max_length=5, verbose_name='L/M')),
                ('supervisor', models.CharField(blank=True, default='', max_length=200)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Invoice #')),
                ('delivery_type', models.CharField(blank=True, choices=[('Delivery', 'Delivery'), ('Pickup', 'Pickup'), ('SR In Store', 'SR In Store')], default='', max_length=20)),
                ('materials', models.CharField(blank=True, default='', max_length=200)),
                ('book_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Book #')),
                ('notes', models.TextField(blank=True, default='')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.supplier')),
                ('type_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.typedescription', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Construction Entry',
                'verbose_name_plural': 'Construction Entries',
                'ordering': ['date', 'id'],
            },
        ),
    ]
