# Generated by Django 6.0.2 on 2026-02-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionentry',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='constructionentry',
            name='estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='constructionentry',
            name='invoiced_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Invoiced Amt'),
        ),
        migrations.AlterField(
            model_name='constructionentry',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='QTY'),
        ),
        migrations.AlterField(
            model_name='constructionentry',
            name='supplies_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='constructionentry',
            name='tax_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Tax/Fees'),
        ),
    ]
